.PHONY: all

all: states.png connecting.png progress.png

states.png: states.dot
	dot -Tpng -o states.png states.dot

connecting.png: connecting.dot
	dot -Tpng -o connecting.png connecting.dot

progress.png: progress.dot
	dot -Tpng -o progress.png progress.dot
